---
- hosts: localhost
  connection: local
  gather_facts: false
  become: true

  vars:
    localip: 192.168.170.69

  tasks:
  - name: Disable SELinux
    ansible.posix.selinux:
      policy: targeted
      state: disabled

  - name: enable http firewall
    ansible.posix.firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled

  - name: Modify nginx conf listener
    ansible.builtin.lineinfile:
      path: /etc/nginx/nginx.conf
      regexp: '{{ localip }}:80 default_server'
      line: "        listen 80 default_server;"
    notify: restart nginx

  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
