---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars:
    localip: "{{ ansible_facts['all_ipv4_addresses'][0] }}"
    nginx_port: 8080/tcp
    port_only: 8080

  tasks:
  - name: Disable SELinux
    ansible.posix.selinux:
      policy: targeted
      state: disabled

  - name: enable http firewall
    ansible.posix.firewalld:
      port: "{{ nginx_port }}"
      permanent: true
      immediate: true
      state: enabled

  - name: Modify nginx config
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: restart nginx

  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
