---
- hosts: localhost
  connection: local
  gather_facts: false
  become: true

  vars:
    localip: 192.168.170.69

  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: present

  - name: Setup web folder
    file:
      path: /var/www/html
      state: directory
      recurse: yes

  - name: Write HTML to index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: Modify nginx conf listener
    ansible.builtin.lineinfile:
      path: /etc/nginx/nginx.conf
      regexp: 'listen\s+80 default_server;'
      line: "        listen {{ localip }}:80 default_server;"
    notify: restart nginx

  - name: Modify nginx conf root
    ansible.builtin.lineinfile:
      path: /etc/nginx/nginx.conf
      regexp: '^\s+root\s+\/usr\/share\/nginx\/html;'
      line: "        root /var/www/html;"
    notify: restart nginx

  - name: start nginx
    systemd:
      name: nginx
      state: started

  - name: Enable SELinux
    ansible.posix.selinux:
      policy: targeted
      state: enforcing

  - name: disable http
    ansible.posix.firewalld:
      service: http
      permanent: true
      immediate: true
      state: disabled

  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
