---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars:
    localip: "{{ ansible_facts['all_ipv4_addresses'][1] }}"
    nginx_port: 8080/tcp
    port_only: 8080
    services:
      - nginx
      - firewalld

  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: present

  - name: Setup web root folder
    file:
      path: /var/www/html
      state: directory
      recurse: yes
      owner: nobody
      group: nobody
      mode: 0760

  - name: Write HTML to index.html
    copy:
      src: data/index.html
      dest: /var/www/html/index.html
 
  - name: Modify nginx config
    template:
      src: data/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: restart nginx

  - name: Modify nginx conf root
    ansible.builtin.lineinfile:
      path: /etc/nginx/nginx.conf
      regexp: '^\s+root\s+\/usr\/share\/nginx\/html;'
      line: "        root /var/www/html;"
    notify: restart nginx

  - name: start services
    systemd:
      name: "{{ item }}"
      state: started
    loop: "{{ services }}"

  - name: Enable SELinux
    ansible.posix.selinux:
      policy: targeted
      state: enforcing

  - name: Block port on firewall
    ansible.posix.firewalld:
      port: "{{ nginx_port }}"
      permanent: true
      immediate: true
      state: disabled

  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
